repos:
  - repo: local
    hooks:
      - id: black
        name: black 
        language: system
        entry: poetry run black
        files: '\.py$'
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        files: '\.py$'
        args: ["--profile", "black"]
